### ISSUE TITLE
Feature request: concurrency

### ISSUE THREAD

**Issue by vanodevium** [tolyo/open-outcry#8]
When I started testing goroutines, I ran into two problems:

- `ERRO[0009] pq: new row for relation "payment_account" violates check constraint "payment_account_check"`
- `ERRO[0007] pq: deadlock detected`

---
Test code is deadly simple:
```
    var wg sync.WaitGroup
	wg.Add(100)
	for i := 0; i < 100; i++ {
		go func() {
			log.Info(services.ProcessTradeOrder(tradingAccount1.Id, "BTC_EUR", "LIMIT", "SELL", 10, 10, "GTC"))
			log.Info(services.ProcessTradeOrder(tradingAccount2.Id, "BTC_EUR", "LIMIT", "SELL", 10, 10, "GTC"))

			log.Info(services.ProcessTradeOrder(tradingAccount1.Id, "BTC_EUR", "MARKET", "BUY", 0, 100, "GTC"))
			log.Info(services.ProcessTradeOrder(tradingAccount2.Id, "BTC_EUR", "MARKET", "BUY", 0, 100, "GTC"))

			wg.Done()
		}()
	}

	wg.Wait()
```
---

I have no idea where the problem is, but maybe we need to think about separate transactions on the code side, as well as optimistic table locks. Or maybe you already have some advice and workaround for this problem?

**Comment by tolyo** [comment]
Good catch. Fixed. So the check was failing due to lack of transaction isolation at the service level. Now, you can still get concurrent update errors. To fully eliminate those, you would still need to make sure that those operations are executed sequentially via a Mutex. At that point we would ask ourselves - what are we optimizing here for? A DDOS attack? The important takeaway here is that the industry practice for matching-engines is to use single-threaded event loops being fed data through a queue on a message broker with guaranteed delivery.
